name: Sync Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2
        with:
          repository: RP-Tama/1TTS-Teknologi-Multimedia-
          ref: main
          
      - name: Push to Repo B
        uses: ad-m/github-push-action@master
        with:
          github_token: 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
          branch: main
          force: true
          directory: './'
