name: Auto Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A
      uses: actions/checkout@v2
      with:
        repository: https://github.com/RP-Tama/1TTS-Teknologi-Multimedia-.git
    
    - name: Pull changes from Repo A
      run: git pull

    - name: Checkout Repo B
      uses: actions/checkout@v2
      with:
        repository: https://github.com/Koro129/tes1.git

    - name: Push changes to Repo B
      run: git push
